### ISSUE TITLE
Step 2 is confusing

### ISSUE THREAD

**Issue by coaxial** [pitkley/docker-paperless#1]
Hey, could you clarify what you mean by this? I don't have a data container, should I have one? Or should I use the volumes from the webserver (as defined in the docker-compose.yml)?

> Create the superuser interactively (adapt paperless_data_1 to your situation):
> 
> `docker run --rm -it --volumes-from paperless_data_1 pitkley/paperless createsuperuser`

**Comment by JamieMagee** [comment]
I think `paperless_data_1` is meant to represent one of the paperless container you spin up. You just need to create an interactive shell to one of them in order to create the superuser account.

It might be easier to just `exec` it in one of the existing containers, instead of spinning up a 3rd paperless container to create a superuser. Something like

`docker exec -it paperless_data_1 ./manage.py createsuperuser`

should work.

**Comment by pitkley** [comment]
Step 2 is a relic back from when Docker didn't support volumes and data-containers were one way to have persistent volumes (see the [old `docker-compose.yml`](https://github.com/pitkley/docker-paperless/blob/a791ea2d0fb2d870f91918b7180908f6e66e9896/docker-compose.yml)).

For an up-to-date documentation, see the [official Paperless docs on Docker](https://paperless.readthedocs.io/en/latest/setup.html#docker-method). Step 2 has been replaced by the following command:

``` console
$ docker-compose run --rm webserver createsuperuser
```

I have updated the README accordingly.
